#!/bin/bash

if [ -n "$1" ]
then
	curl \
	   -u $1:$2 \
	   -X GET \
	   -H "Content-Type: application/json" \
	   'https://jira.iconsolutions.com/jira/rest/api/2/search?jql=Squad%20%3D%20"Spice%20Merchants"%20AND%20status%20changed%20to%20created%20after%20-2d' \
		| jq '.issues' | jq -r '.[].key'

else 
    echo "Provide jira credentials"
fi

