#!/bin/bash

curl -s --connect-timeout 5 -A '/u/deliveryninja' \
'https://www.reddit.com/r/'$1'/top.json?sort=top&t=today&limit=10' | \
python2.7 -c 'import sys, random, json; randnum = random.randint(0,9); response = json.load(sys.stdin)["data"]["children"][randnum]["data"]; print response["title"];'
